workspace = { members = ["device_driver_project"] }
[package]
name = "fibonacci-sequence_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
